trigger:
  - main
  - feature/*
  - bugfix/*
  - release/*

pool:
  vmImage: "ubuntu-latest"

variables:
  # Node.js version
  nodeVersion: "18.x"

  # Environment variables
  dev_port: 3000
  qa_port: 3001
  staging_port: 3002
  prod_port: 3003

  # Build artifact
  buildArtifactName: "app-build"

  # Development environment variables
  dev_node_env: "development"
  dev_api_version: "v1"
  dev_log_level: "debug"
  dev_cors_origin: "http://localhost:3000"

  # QA environment variables
  qa_node_env: "qa"
  qa_api_version: "v1"
  qa_log_level: "info"
  qa_cors_origin: "https://qa.example.com"

  # Staging environment variables
  staging_node_env: "staging"
  staging_api_version: "v1"
  staging_log_level: "info"
  staging_cors_origin: "https://staging.example.com"

  # Production environment variables
  prod_node_env: "production"
  prod_api_version: "v1"
  prod_log_level: "error"
  prod_cors_origin: "https://example.com"

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: Build
        displayName: "Build and Test"
        steps:
          # Checkout source code with full history
          - checkout: self
            fetchDepth: 0
            displayName: "Checkout source code"

          # Setup Node.js
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: $(nodeVersion)

          # Install dependencies
          - script: |
              npm ci
            displayName: "Install dependencies"

          # Lint code
          - script: |
              npm run lint
            displayName: "Run ESLint"
            continueOnError: true

          # Run tests with coverage
          - script: |
              npm test
            displayName: "Run tests with coverage"

          # Archive build artifacts
          - task: ArchiveFiles@2
            displayName: "Archive app files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(buildArtifactName).zip"
              replaceExistingArchive: true
              excludePattern: "node_modules/**|.git/**|.gitignore|README.md|coverage/**|.vscode/**"

          # Publish build artifacts
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact"
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"

  - stage: DeployToDev
    displayName: "Deploy to Development"
    dependsOn: CI
    condition: succeeded()
    jobs:
      - job: DeployToDev
        displayName: "Deploy to Dev Environment"
        steps:
          # Download build artifact
          - task: DownloadBuildArtifacts@1
            displayName: "Download Build Artifacts"
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "drop"
              downloadPath: "$(System.ArtifactsDirectory)"

          # Extract the artifact
          - task: ExtractFiles@1
            displayName: "Extract Files"
            inputs:
              archiveFilePatterns: "$(System.ArtifactsDirectory)/drop/$(buildArtifactName).zip"
              destinationFolder: "$(System.DefaultWorkingDirectory)/app"
              cleanDestinationFolder: true

          # Install dependencies for deployment
          - script: |
              cd $(System.DefaultWorkingDirectory)/app
              npm ci --production
            displayName: "Install Production Dependencies"

          # Start the application
          - script: |
              cd $(System.DefaultWorkingDirectory)/app
              export NODE_ENV=$(dev_node_env)
              export PORT=$(dev_port)
              export API_VERSION=$(dev_api_version)
              export LOG_LEVEL=$(dev_log_level)
              export CORS_ORIGIN=$(dev_cors_origin)
              node app.js &
              echo "Application deployed to Dev environment on port $(dev_port)"
              sleep 5
              curl http://localhost:$(dev_port)
              kill $(lsof -t -i:$(dev_port)) || true
            displayName: "Deploy to Dev Environment"

  - stage: DeployToQA
    displayName: "Deploy to QA"
    dependsOn: DeployToDev
    condition: succeeded()
    jobs:
      - deployment: DeployToQA
        displayName: "Deploy to QA Environment"
        environment:
          name: QA
          resourceType: VirtualMachine
          tags: qa
        strategy:
          runOnce:
            deploy:
              steps:
                # Download build artifact
                - task: DownloadBuildArtifacts@1
                  displayName: "Download Build Artifacts"
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                # Extract the artifact
                - task: ExtractFiles@1
                  displayName: "Extract Files"
                  inputs:
                    archiveFilePatterns: "$(System.ArtifactsDirectory)/drop/$(buildArtifactName).zip"
                    destinationFolder: "$(System.DefaultWorkingDirectory)/app"
                    cleanDestinationFolder: true

                # Install dependencies
                - script: |
                    cd $(System.DefaultWorkingDirectory)/app
                    npm ci --production
                  displayName: "Install Production Dependencies"

                # Deploy to QA environment
                - script: |
                    cd $(System.DefaultWorkingDirectory)/app
                    export NODE_ENV=$(qa_node_env)
                    export PORT=$(qa_port)
                    export API_VERSION=$(qa_api_version)
                    export LOG_LEVEL=$(qa_log_level)
                    export CORS_ORIGIN=$(qa_cors_origin)
                    node app.js &
                    echo "Application deployed to QA environment on port $(qa_port)"
                    sleep 5
                    curl http://localhost:$(qa_port)
                    kill $(lsof -t -i:$(qa_port)) || true
                  displayName: "Deploy to QA Environment"

  - stage: DeployToStaging
    displayName: "Deploy to Staging"
    dependsOn: DeployToQA
    condition: succeeded()
    jobs:
      - deployment: DeployToStaging
        displayName: "Deploy to Staging Environment"
        environment:
          name: Staging
          resourceType: VirtualMachine
          tags: staging
        strategy:
          runOnce:
            deploy:
              steps:
                # Download build artifact
                - task: DownloadBuildArtifacts@1
                  displayName: "Download Build Artifacts"
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                # Extract the artifact
                - task: ExtractFiles@1
                  displayName: "Extract Files"
                  inputs:
                    archiveFilePatterns: "$(System.ArtifactsDirectory)/drop/$(buildArtifactName).zip"
                    destinationFolder: "$(System.DefaultWorkingDirectory)/app"
                    cleanDestinationFolder: true

                # Install dependencies
                - script: |
                    cd $(System.DefaultWorkingDirectory)/app
                    npm ci --production
                  displayName: "Install Production Dependencies"

                # Deploy to Staging environment
                - script: |
                    cd $(System.DefaultWorkingDirectory)/app
                    export NODE_ENV=$(staging_node_env)
                    export PORT=$(staging_port)
                    export API_VERSION=$(staging_api_version)
                    export LOG_LEVEL=$(staging_log_level)
                    export CORS_ORIGIN=$(staging_cors_origin)
                    node app.js &
                    echo "Application deployed to Staging environment on port $(staging_port)"
                    sleep 5
                    curl http://localhost:$(staging_port)
                    kill $(lsof -t -i:$(staging_port)) || true
                  displayName: "Deploy to Staging Environment"

  - stage: DeployToProduction
    displayName: "Deploy to Production"
    dependsOn: DeployToStaging
    condition: succeeded()
    jobs:
      - deployment: DeployToProduction
        displayName: "Deploy to Production Environment"
        environment:
          name: Production
          resourceType: VirtualMachine
          tags: production
        strategy:
          runOnce:
            deploy:
              steps:
                # Download build artifact
                - task: DownloadBuildArtifacts@1
                  displayName: "Download Build Artifacts"
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                # Extract the artifact
                - task: ExtractFiles@1
                  displayName: "Extract Files"
                  inputs:
                    archiveFilePatterns: "$(System.ArtifactsDirectory)/drop/$(buildArtifactName).zip"
                    destinationFolder: "$(System.DefaultWorkingDirectory)/app"
                    cleanDestinationFolder: true

                # Install dependencies
                - script: |
                    cd $(System.DefaultWorkingDirectory)/app
                    npm ci --production
                  displayName: "Install Production Dependencies"

                # Deploy to Production environment
                - script: |
                    cd $(System.DefaultWorkingDirectory)/app
                    export NODE_ENV=$(prod_node_env)
                    export PORT=$(prod_port)
                    export API_VERSION=$(prod_api_version)
                    export LOG_LEVEL=$(prod_log_level)
                    export CORS_ORIGIN=$(prod_cors_origin)
                    node app.js &
                    echo "Application deployed to Production environment on port $(prod_port)"
                    sleep 5
                    curl http://localhost:$(prod_port)
                    kill $(lsof -t -i:$(prod_port)) || true
                  displayName: "Deploy to Production Environment"
